import mongoose from "mongoose";
import GRN from "../models/GRN.js";
import MaterialRequest from "../models/MaterialRequest.js";
import PurchaseOrder from "../models/PurchaseOrder.js";
import StockRequest from "../models/StockRequest.js";
import Stock from "../models/Stock.js";
import StockLedger from "../models/stockLedgerSchema.js";
import { applyStockLedgerEntry } from "../utils/inventory.js";
import { logAudit } from "../utils/audit.js";

export const createGRN=async(req,res)=>{const session=await mongoose.startSession();try{const {materialRequestId,purchaseOrderId,stockRequestId,procurementId,deliveryChallan,dispatchDate,vehicleNumber,driverName,items}=req.body;if(!items?.length)return res.status(400).json({message:"items required"});await session.withTransaction(async()=>{let projectId=null,po=null,mr=null;if(purchaseOrderId){po=await PurchaseOrder.findById(purchaseOrderId).session(session);if(!po)throw new Error("Purchase order not found");if(!["ORDERED","PARTIALLY_RECEIVED"].includes(String(po.status).toUpperCase()))throw new Error("PO must be ORDERED before receiving");projectId=po.projectId;}else if(materialRequestId){mr=await MaterialRequest.findById(materialRequestId).session(session);if(!mr)throw new Error("Material Request not found");projectId=mr.projectId;}else throw new Error("purchaseOrderId or materialRequestId is required");
const grn=new GRN({materialRequestId:materialRequestId||null,purchaseOrderId:purchaseOrderId||null,stockRequestId:stockRequestId||null,procurementId:procurementId||null,projectId,poNumber:po?.poNumber||mr?.poNumber,deliveryChallan,dispatchDate,vehicleNumber,driverName,receivedBy:req.user.id,items});await grn.save({session});
for(const it of items){const received=Number(it.receivedQty||0),damaged=Number(it.damagedQty||0),returned=Number(it.returnQty||0),accepted=it.acceptedQty!==undefined?Number(it.acceptedQty):Math.max(received-damaged-returned,0);if(received<0||damaged<0||returned<0||accepted<0||accepted>received)throw new Error("Invalid GRN quantities");await applyStockLedgerEntry({projectId,itemId:it.itemId,qtyChange:accepted,transactionType:"GRN",referenceId:grn._id,referenceNumber:grn.poNumber,remarks:"Material received via GRN",session});
if(po){const line=po.items.find(x=>String(x.itemId)===String(it.itemId));if(!line)throw new Error("GRN item is not part of Purchase Order");line.receivedQty=Number(line.receivedQty||0)+accepted;if(line.receivedQty>Number(line.qty))throw new Error("Received quantity exceeds ordered quantity");}}
if(po){const complete=po.items.every(i=>Number(i.receivedQty||0)>=Number(i.qty));const any=po.items.some(i=>Number(i.receivedQty||0)>0);po.status=complete?"RECEIVED":(any?"PARTIALLY_RECEIVED":"ORDERED");po.receivedHistory.push({grnId:grn._id,receivedAt:new Date(),receivedBy:req.user.id});await po.save({session});}
if(stockRequestId){const sr=await StockRequest.findById(stockRequestId).session(session);if(sr){const totalAccepted=items.filter(i=>String(i.itemId)===String(sr.materialId)).reduce((a,i)=>a+(i.acceptedQty!==undefined?Number(i.acceptedQty):Math.max(Number(i.receivedQty||0)-Number(i.damagedQty||0)-Number(i.returnQty||0),0)),0);const fulfilled=(Number(sr.fulfilledQty||0)+totalAccepted);sr.fulfilledQty=fulfilled;sr.status=fulfilled>=Number(sr.quantity)?"FULFILLED":"PARTIALLY_FULFILLED";await sr.save({session});}}
await logAudit({module:"GRN",entityId:grn._id,action:"created",performedBy:req.user.id,projectId,session});res.status(201).json({message:"GRN created successfully",grn});});}catch(err){if(!res.headersSent)res.status(400).json({message:"GRN error",error:err.message});}finally{session.endSession();}};
export const getGRN=async(req,res)=>{try{const grn=await GRN.findById(req.params.id).populate("materialRequestId","poNumber projectId").populate("purchaseOrderId","status projectId").populate("items.itemId","name unit").populate("receivedBy","name");if(!grn)return res.status(404).json({message:"GRN not found"});res.json({message:"GRN fetched",grn});}catch(err){res.status(500).json({message:"Error fetching GRN",error:err.message});}};
export const listGRNs=async(req,res)=>{try{const f={};if(req.query.projectId)f.projectId=req.query.projectId;const grns=await GRN.find(f).populate("purchaseOrderId","status").populate("receivedBy","name").sort({createdAt:-1});res.json({message:"GRNs fetched",grns});}catch(err){res.status(500).json({message:"Error listing GRNs",error:err.message});}};
export const getProjectStock=async(req,res)=>{try{const {projectId}=req.params;const projectStock=await Stock.find({projectBalances:{$elemMatch:{projectId}}}).populate("itemId","name unit");res.json({stock:projectStock.map(st=>{const pb=st.projectBalances.find(p=>String(p.projectId)===String(projectId));return {itemId:st.itemId?._id,name:st.itemId?.name,unit:st.itemId?.unit,qty:pb?.qty||0,damaged:st.damaged||0};})});}catch(err){res.status(500).json({message:"Project Stock Error",error:err.message});}};
export const getItemHistory=async(req,res)=>{try{const logs=await StockLedger.find({itemId:req.params.itemId,projectId:req.params.projectId}).sort({createdAt:-1});res.json({history:logs});}catch(err){res.status(500).json({message:"Ledger error",error:err.message});}};
